### ISSUE TITLE
Roadmap for Sherpa Docker to production

### ISSUE THREAD

**Issue by Starefossen** [Turistforeningen/sherpa#60]
This issue attempts to outline the roadmap for deploying new Sherpa Docker setup to production.

**Deployment plan:**

1. Build Sherpa Docker containers
2. Put Sherpa in maintenance mode
3. Import production database
4. Update load balancer to route traffic to Sherpa Docker 

**Pain points:**

* [x] Persisting database between Docker Compose builds
* [x] Zero downtime is not possible with Docker Compose
* [x] Tedious to configure Hipache with multiple domains for same backend (error prone)
* [x] Memcached is cleared between builds, will this be a problem?
* [x] AWS server memory usage 

**Blockers:**

* [x] New database backup routines
* [x] Sherpa Docker with production settings #59 
* [x] Build configurations for frontend assets #54
* [x] [Docker Compose v1.2.0](https://github.com/docker/compose/releases) ([extending docker-compose.yml](https://github.com/docker/compose/blob/master/docs/yml.md#extends))
* [x] CORS handling for API requests
* [x] Cron tasks
* [x] S3 bucket SSL / boto issue

-------

## Vanilla Docker with Haproxy

Since Docker Compose lacks support for minimal downtime deployments it is worth to evaluate wether at vanilla Docker setup with a Haproxy load balancer in front is a better fit. The setup will look something like this:

![sherpa-docker-prod-architecture](https://cloud.githubusercontent.com/assets/968267/6726924/43108dfc-ce1d-11e4-95d8-b011febda117.png)

In this setup the Postgres database runs independent form the rest of the containers in the sense that it is not rebuild between builds. Another important difference with setup is that the database migration is run before traffic is routed to the new build. **In other words;** *all database migrations must be fully backward compatible with the previous deployed version.*

**Deployment story:**

1. Clone sherpa repository into a new directory
2. Init git submodule
3. Install and build fronted assets (`builder`) 
4. Build application containers (`nginx`, `django`, `memcached`)
5. Run database migrations
6. Start the new Sherpa containers
7. Route traffic to the new Sherpa containers
8. Stop the old Sherpa containers

**Comment by kvikshaug** [comment]
Note that we're upgrading Python to >=2.7.9 [which verifies certificates by default](https://www.python.org/dev/peps/pep-0476/); which means that our S3 connections will not work as `boto` takes the bucket name and not endpoint URL as input. See also [this boto issue](https://github.com/boto/boto/issues/2836).
